FROM heroku-opencv
RUN pip3 install flask
RUN pip3 install gunicorn
RUN pip3 install oauth2

RUN mkdir -p /opt
ADD ./backend /opt
ADD ./viewer/dist /opt
ADD ./getTagApi.py /opt
WORKDIR /opt

CMD gunicorn getTagApi:app --log-file=-


RUN apt-get install -y nodejs \
    npm
RUN npm cache clean
RUN npm install n -g
RUN n stable
RUN ln -sf /usr/local/bin/node /usr/bin/node
